version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/online_shop?schema=public
    depends_on:
      - db

  db:
    image: postgres:15.6
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_shop
    ports:
      - "8888:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/online_shop?schema=public
    depends_on:
      - db
      - app
    command: |
      sh -c "
        sleep 15 &&
        npx prisma migrate deploy &&
        npx prisma db seed
      "

volumes:
  postgres-data: